name: deno_embedded_commands

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@main
        with:
          deno-version: "1.21.0"
      - name: Run fmt
        run: |
          deno fmt --check
      - name: check
        run: |
          pwd
      - name: Run lint
        run: |
          deno lint
      - name: Run tests
        run: |
          deno test --allow-read --allow-env --allow-net
